const data = [
  {
    _id: "t1",
    author: "Bryan",
    name: "Shopping",
    createdAt: new Date(),
    updatedAt: new Date(),
    updatedBy: "Bryan",
    isTaskGroup: false,
    partOfGroups: ["root"],
    status: "default",
  },
  {
    _id: "t2",
    author: "Bryan",
    name: "Be great to each other",
    createdAt: new Date(),
    updatedAt: new Date(),
    updatedBy: "You",
    isTaskGroup: false,
    partOfGroups: ["root"],
    status: "finished",
  },
  {
    _id: "g1",
    author: "You",
    name: "Lots Of stuff",
    createdAt: new Date(),
    updatedAt: new Date(),
    updatedBy: "Bryan",
    isTaskGroup: true,
    partOfGroups: ["root"],
    status: "default",
  },
  {
    _id: "t3",
    author: "You",
    name: "Be present",
    createdAt: new Date(),
    updatedAt: new Date(),
    updatedBy: "You",
    isTaskGroup: false,
    partOfGroups: ["g1"],
    status: "default",
  },
  {
    _id: "t4",
    author: "You",
    name: "Do meditation",
    createdAt: new Date(),
    updatedAt: new Date(),
    updatedBy: "You",
    isTaskGroup: false,
    partOfGroups: ["root", "g1"],
    status: "finished",
  },
];

export default data;
